In [2]:
# python list
# list comprehension
# array module (import lib array)
# numpy array : 
#       zeros
#       ones
#       full
#       eye
#       arange
#       reshape
#       indexing

In [3]:
import numpy as np

In [4]:
np.__version__

'2.0.1'

In [5]:
get_ipython().run_line_magic('pinfo', 'np.zeros')

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [6]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [7]:
arr = np.arange(0,100)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [10]:
get_ipython().run_line_magic('pinfo', 'np.arange')


Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [11]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [12]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [13]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
# Difference between List and Numpy Array.
"In list, we can store different datatype elements. And in Numpy Array we can only store any 1 datatype elements."
"Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype."

'Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype.'

In [15]:
l2 = [ x for x in range(0,10)]

In [16]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
l3 = [str(x) for x in l2]

In [18]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [19]:
l4 = [x**2 for x in l2]

In [20]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [21]:
type(l4)

list

In [22]:
import array

In [23]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating-point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [24]:
arr = array.array('i', l2)

In [25]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
type(arr)

array.array

In [27]:
arr1 = array.array('i',[x**2 for x in l2])

In [28]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [29]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.array([x + 3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
np.array([x - 3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [32]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [33]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [34]:
np.array([1,2,3,4,5],dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [35]:
l2d = [[1,2,3],[4,5,6]]

In [36]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [37]:
lc2d = [range(i,i+3) for i in [1,4,7]]

In [38]:
np.array(lc2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [44]:
arr = np.ones([10,10], dtype = int)

In [45]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
arr[4:6,4:6] = 1

In [47]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [48]:
arr = np.ones([3,3],dtype = int)

In [49]:
3.1*arr

array([[3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1]])

In [50]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [51]:
arr = np.eye(3,dtype = int)

In [52]:
np.transpose(arr)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
ar1 = np.ones([6,6], dtype = int)

In [54]:
64*ar1

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [55]:
np.full([6,6], 64, dtype = int)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [56]:
#linspace function => Linearly spaced elements.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [58]:
import numpy as np

In [59]:
#shallow copy
a=np.arange(1,10).reshape(3,3)

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [62]:
#deep copy
da=a[:2,:2].copy()

In [63]:
da

array([[1, 2],
       [4, 5]])

In [64]:
a[0,0]=11

In [65]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [66]:
da

array([[1, 2],
       [4, 5]])

In [67]:
da[1,1]=5

In [68]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [69]:
c=np.arange(1,5)
c

array([1, 2, 3, 4])

In [70]:
c.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [71]:
ar=np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
import numpy as np

In [73]:
ar.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [74]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
ar.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [76]:
ar.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
ar=ar.flatten()
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
ar[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

concatenation , joining of two arrays

In [79]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [80]:
np.concatenate([ar,c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4])

In [81]:
np.concatenate([ar,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
np.concatenate([ar,c],axis=0)
# axis to specify row 0/ column 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4])

In [ ]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x0000011B54618E00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

In [ ]:
#Stack arrays in sequence vertically (row wise)
a=np.arange(9,18).reshape(3,3)

In [ ]:
np.vstack((a,ap))

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [ 1,  2,  3]])

In [ ]:
np.hstack((a,ad))

array([[ 9, 10, 11,  1],
       [12, 13, 14,  2],
       [15, 16, 17,  3]])

In [ ]:
ad=np.arange(1,4)
ad=ad[:,np.newaxis]

In [ ]:
ap=np.arange(1,4)


In [ ]:
np.split?


Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000011B54745D00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [ ]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x0000011B54745C60>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.

In [ ]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000011B54745D00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [ ]:
np.dsplit?

Signature:       np.dsplit(ary, indices_or_sections)
Call signature:  np.dsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function dsplit at 0x0000011B54745DA0>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split array into multiple sub-arrays along the 3rd axis (depth).

Please refer to the `split` documentation.  `dsplit` is equivalent
to `split` with ``axis=2``, the array is always split along the third
axis provided the array dimension is greater than or equal to 3.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(2, 2, 4)
>>> x
array([[[ 0.,   1.,   2.,   3.],
        [ 4.,   5.,   6.,   7.]],
       [[ 8.,   9.,  10.,  11.],
        [12.,  13.,  14.,  15.]]])
>>> np.dsplit(x, 2)
[array([[[ 0.,  1.],
        [ 4.,  5.]],
       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2

In [ ]:
A=np.array([1,2,3,4,5,6])
A

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Number split in a range 
np.split(A,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
np.vsplit(a,[1,2])

[array([[ 9, 10, 11]]), array([[12, 13, 14]]), array([[15, 16, 17]])]

In [ ]:
np.hsplit(a,[1,2])

[array([[ 9],
        [12],
        [15]]),
 array([[10],
        [13],
        [16]]),
 array([[11],
        [14],
        [17]])]

In [ ]:
t=np.arange(1,28).reshape(3,3,3)
t

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
np.dsplit(t,3)

[array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]),
 array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]

In [ ]:
import numpy as np

In [ ]:
r=np.arange(1,10).reshape(3,3)
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(r)

np.int64(45)

In [ ]:
np.sum(r,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(r,axis=1)

array([ 6, 15, 24])

In [ ]:
np.min(r)

np.int64(1)

In [ ]:
np.max(r)

np.int64(9)

In [ ]:
# Index of min
np.argmin(r)

np.int64(0)

In [ ]:
# Index of max
np.argmax(r)

np.int64(8)

In [ ]:
np.abs(r)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.var(r)

np.float64(6.666666666666667)

In [ ]:
np.std(r)

np.float64(2.581988897471611)

In [ ]:
np.median(r)

np.float64(5.0)

In [ ]:
np.prod(r)

np.int64(362880)

In [ ]:
import numpy as np

In [ ]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, device=None, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ens

Assignment 1

1. Import Numpy as np
2. Create an array of 10 zeros
3. Create an array of 10 ones
4. Create an array of the integers from 10 to 50
5. Create an array of all the even integers from 10 to 50
6. Create a 3x3 matrix with values ranging from 0 to 8
7. Create a 3x3 identity matrix
8. use NumPy to generate a random number between 0 to 1
9. Use Numpy to generate an array of 25 random numbers sampled from
a standard normal distribution
10. Create a matrix of 10x10 matrix of linearly spaced elements from
0.01 to 1
11. Create an array of 20 linearly spaced points between 0 and 1
12. Create a 5x5 matrix as
array([[ 1, 2, 3, 4, 5],
       [ 6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
find following using slicing
a. array([[12, 13, 14, 15],
          [17, 18, 19, 20],
          [22, 23, 24, 25]])
b. 20
c. array([[ 2],
         [ 7],
         [12]])
d.array([21, 22, 23, 24, 25])
e.array([[16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])
13. Get sum of all values in matrix
14. Get sum of all the columns in matrix
15. Get Standard deviation , varience , minimum, maximum from matrix
row wis.
16. create 2 d matrix with all border values nan

In [ ]:
# 1
import numpy as np

In [ ]:
# 2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# 4
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# 5
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# 6
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# 7
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 8
np.random.random(1)

array([0.38498464])

In [ ]:
# 9
np.random.randn(25)

array([-1.12286818, -0.29239698,  0.07320961, -0.72385004,  0.02890002,
       -0.37582019,  0.16042519, -0.61436246,  0.16244825,  0.10776839,
       -1.29734629,  1.18396284,  0.52880584,  0.52728267,  1.494251  ,
       -1.40177434, -0.49048152, -2.23470619,  0.37255754, -1.48950471,
       -0.93416923,  0.02329694, -0.87623431, -0.61373799, -0.07350226])

In [ ]:
# 10
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [ ]:
# 11
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [83]:
# 12
e=np.arange(1,26).reshape(5,5)
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# 12a
e[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# 12b
e[3,4]

np.int64(20)

In [ ]:
# 12c
e[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# 12d
e[4]

array([21, 22, 23, 24, 25])

In [ ]:
# 12e
e[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# 13
np.sum(e)

np.int64(325)

In [ ]:
# 14
np.sum(e,axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# 15
std= np.std(e, axis=1)
var= np.var(e, axis=1)
min= np.min(e, axis=1)
max= np.max(e, axis=1)

display(std,var,min,max)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

array([2., 2., 2., 2., 2.])

array([ 1,  6, 11, 16, 21])

array([ 5, 10, 15, 20, 25])

In [182]:
# 16
import numpy as np

rows, cols = 5, 5

N= np.zeros((rows, cols))

N[0, :] = np.nan  
N[-1, :] = np.nan
N[:, 0] = np.nan
N[:, -1] = np.nan

display(N)


array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])

Assignment 2

In [85]:
import numpy as np

1. Create 1-D, 2-D and 3-D numpy array
2. Print data type of array.
3. Print shape and dimensions of all the three different array.
4. Create another 1-D array of 12 elements filled with zero
5. Create another 2-D array elements filled with ones.
6. Create a 1-D array known as Maths Marks out of 100 having 20
elements.
7. Sort the above array in ascending and descending order.
8. Create a copy of sorted array to another variable by deep copying.
9. Create 2-D array of 5x5 which is an identity matrix and then convert
1D .
10. Create 2-D array of 3x3. Add one more row to it.
11. Split above array created vertically and horizontally.
12. Create 4x4 identity matrix. Add 4 to each element.
13. Create 1-D array. Initialize with floating point values. Display its ceil,
floor and round (with 2 decimal’s).
14. Create 5x5 matrix. Display min, max, variance and standard
deviation column-wise.
15. Create a null vector of size 10 with 6th value filled with 200.
16. Create a 1-D Array/Vector with values ranging from 100 to 150 in
sequence.
17. Reverse the above vector.
18. Create a 5x5 matrix with values ranging from 0-24 using some
function.
19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]
20. Create a 10x10 matrix with 1 on the borders and 0 inside.
21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
22. Create two 3x3 matrix with random integer values. Perform matrix
addition, multiplication and subtraction

In [87]:
# 1
q=np.arange(4)
r=np.arange(4).reshape(2,2)
s=np.arange(8).reshape(2,2,2)

display(q,r,s)

array([0, 1, 2, 3])

array([[0, 1],
       [2, 3]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [88]:
# 2
s.dtype

dtype('int64')

In [181]:
# 3
display(q,q.shape,q.ndim)
display(r,r.shape,r.ndim)
display(s,s.shape,s.ndim)

array([0, 1, 2, 3])

(4,)

1

array([-1.23,  2.34,  3.45, -4.56])

(4,)

1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

(2, 2, 2)

3

In [177]:
# 4
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
# 5
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
# 6
g=np.random.randint(0, 101, 20)
display(g)

array([ 86,  65,  92,  42,  63,  65,  83,  74,  31,  60,  34, 100,  71,
        77,  17,   1,  35,  84,  94,  80], dtype=int32)

In [116]:
# 7
i=np.sort(g)
j=np.sort(g)[::-1]
display(i,j)

array([  1,  17,  31,  34,  35,  42,  60,  63,  65,  65,  71,  74,  77,
        80,  83,  84,  86,  92,  94, 100], dtype=int32)

array([100,  94,  92,  86,  84,  83,  80,  77,  74,  71,  65,  65,  63,
        60,  42,  35,  34,  31,  17,   1], dtype=int32)

In [129]:
# 8
display(s)
np.sort(s)
l=s.copy()
l[0]=55
display(l,s)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[55, 55],
        [55, 55]],

       [[ 4,  5],
        [ 6,  7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [131]:
# 9
m=np.eye(5)
f=m.flatten()
display(m,f)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [145]:
# 10
t=np.arange(1,10).reshape(3,3)
t2=np.arange(10,13).reshape(1,3)
t3=np.concatenate((t,t2), axis=0)
display(t,t2,t3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[10, 11, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [159]:
# 11
v=np.vsplit(t3,2)
h=np.hsplit(t3,3)
display(v,h)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [161]:
# 12
i=np.eye(4)
i2=i+4
display(i,i2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [167]:
# 13
x=np.array([-1.23,2.34,3.45,-4.56])
e=np.ceil(x)
o=np.floor(x)
r=np.round(x, 2)
display(x,e,o,r)

array([-1.23,  2.34,  3.45, -4.56])

array([-1.,  3.,  4., -4.])

array([-2.,  2.,  3., -5.])

array([-1.23,  2.34,  3.45, -4.56])

In [172]:
# 14
m=np.arange(5,30).reshape(5,5)
min=np.min(m,axis=0)
max=np.max(m,axis=0)
var=np.var(m,axis=0)
std=np.std(m,axis=0)
display(m,min,max,var,std)


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([5, 6, 7, 8, 9])

array([25, 26, 27, 28, 29])

array([50., 50., 50., 50., 50.])

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [173]:
# 15
n=np.zeros(10)
n[5]=200
display(n)

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [184]:
# 16
d=np.arange(100,151)
display(d)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [186]:
# 17
y=d[::-1]
display(y)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [188]:
# 18
r=np.array([1,0,2,0,0,4,0,8])
c=np.nonzero(r)[0]
display(r,c)

array([1, 0, 2, 0, 0, 4, 0, 8])

array([0, 2, 5, 7])

In [192]:
# 19
mat=np.zeros((10,10),dtype=int)
mat[0,:]=1
mat[-1,:]=1
mat[:,0]=1
mat[:,-1]=1
display(mat)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [194]:
# 20
u=np.zeros((8,8),dtype=int)
u[1::2,::2]=1
u[::2,1::2]=1
display(u)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [196]:
# 22
m1=np.random.randint(1,10, size=(3, 3))
m2=np.random.randint(1,10, size=(3, 3))
add=m1+m2
mul=np.dot(m1,m2)
sub=m1-m2
display(m1,m2,add,mul,sub)

array([[2, 5, 7],
       [6, 4, 7],
       [8, 2, 3]], dtype=int32)

array([[8, 4, 7],
       [2, 8, 2],
       [3, 2, 9]], dtype=int32)

array([[10,  9, 14],
       [ 8, 12,  9],
       [11,  4, 12]], dtype=int32)

array([[ 47,  62,  87],
       [ 77,  70, 113],
       [ 77,  54,  87]], dtype=int32)

array([[-6,  1,  0],
       [ 4, -4,  5],
       [ 5,  0, -6]], dtype=int32)