In [3]:
# python list
# list comprehension
# array module (import lib array)
# numpy array : 
#       zeros
#       ones
#       full
#       eye
#       arange
#       reshape
#       indexing

In [4]:
import numpy as np

In [5]:
np.__version__

'2.0.1'

In [6]:
get_ipython().run_line_magic('pinfo', 'np.zeros')

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [7]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [8]:
arr = np.arange(0,100)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
get_ipython().run_line_magic('pinfo', 'np.arange')


Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [12]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [13]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [14]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
# Difference between List and Numpy Array.
"In list, we can store different datatype elements. And in Numpy Array we can only store any 1 datatype elements."
"Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype."

'Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype.'

In [16]:
l2 = [ x for x in range(0,10)]

In [17]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
l3 = [str(x) for x in l2]

In [19]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
l4 = [x**2 for x in l2]

In [21]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [22]:
type(l4)

list

In [23]:
import array

In [24]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [25]:
arr = array.array('i', l2)

In [26]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
type(arr)

array.array

In [28]:
arr1 = array.array('i',[x**2 for x in l2])

In [29]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [30]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.array([x + 3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
np.array([x - 3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [33]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [34]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [35]:
np.array([1,2,3,4,5],dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [36]:
l2d = [[1,2,3],[4,5,6]]

In [37]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [38]:
lc2d = [range(i,i+3) for i in [1,4,7]]

In [39]:
np.array(lc2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [42]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [45]:
arr = np.ones([10,10], dtype = int)

In [46]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [47]:
arr[4:6,4:6] = 1

In [48]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [49]:
arr = np.ones([3,3],dtype = int)

In [50]:
3.1*arr

array([[3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1]])

In [51]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [52]:
arr = np.eye(3,dtype = int)

In [53]:
np.transpose(arr)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
ar1 = np.ones([6,6], dtype = int)

In [55]:
64*ar1

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [56]:
np.full([6,6], 64, dtype = int)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [57]:
#linspace function => Linearly spaced elements.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [58]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [59]:
import numpy as np

In [60]:
#shallow copy
a=np.arange(1,10).reshape(3,3)

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [63]:
#deep copy
da=a[:2,:2].copy()

In [64]:
da

array([[1, 2],
       [4, 5]])

In [65]:
a[0,0]=11

In [66]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [67]:
da

array([[1, 2],
       [4, 5]])

In [68]:
da[1,1]=5

In [112]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
c=np.arange(1,5)
c

array([1, 2, 3, 4])

In [71]:
c.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [111]:
ar=np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
import numpy as np

In [74]:
ar.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [75]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [76]:
ar.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [77]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [78]:
ar=ar.flatten()
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [79]:
ar[:,np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

concatenation , joining of two arrays

In [80]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [81]:
np.concatenate([ar,c])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4])

In [82]:
np.concatenate([ar,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [ ]:
np.concatenate([ar,c],axis=0)
# axis to specify row 0/ column 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25,  1,  2,  3,  4])

In [ ]:
import numpy as np

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.random.random(100)

array([0.12505952, 0.07437785, 0.34394058, 0.58278529, 0.64445716,
       0.06501186, 0.86034108, 0.32937383, 0.77756702, 0.10953476,
       0.49044551, 0.24729946, 0.81796524, 0.24677   , 0.32462238,
       0.60210771, 0.95101201, 0.61812798, 0.03798289, 0.5324821 ,
       0.64857357, 0.51844396, 0.50992716, 0.76963934, 0.60636085,
       0.46574071, 0.18961149, 0.35367748, 0.92021626, 0.83449354,
       0.12181567, 0.02996785, 0.186822  , 0.85744448, 0.27227208,
       0.1513542 , 0.75349714, 0.87130394, 0.17227073, 0.97193081,
       0.95367456, 0.17631651, 0.16526163, 0.75206895, 0.20636797,
       0.42288406, 0.23959966, 0.33157157, 0.19916469, 0.33609597,
       0.74225086, 0.08848244, 0.55780181, 0.11147969, 0.66325204,
       0.74110298, 0.38521843, 0.84276923, 0.55569259, 0.88603407,
       0.10850549, 0.40940668, 0.78082146, 0.45772407, 0.26458868,
       0.36257804, 0.76811425, 0.18494669, 0.49805874, 0.69935042,
       0.65038441, 0.96669005, 0.41515552, 0.23946652, 0.17686

In [87]:
ds=np.random.randn(25)
ds

array([ 0.32329624,  0.7846688 , -2.31841747, -0.12464883,  0.61002316,
       -1.0000808 ,  0.743214  , -0.74915635, -1.89045082,  0.28632012,
        0.08999631,  0.34687623,  1.07988694,  1.22250428, -0.60828062,
       -1.34750839,  1.72002171, -0.44229733, -1.10494285,  0.97516581,
       -0.48538532, -2.08988458, -0.1041912 , -0.52361038, -2.06059154])

In [91]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [92]:
np.linspace(0.,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [96]:
e=np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [150]:
e=np.arange(1,26).reshape(5,5)
print(e[1,2::5,5])

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [107]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x0000011B54618E00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\_core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

In [117]:
#Stack arrays in sequence vertically (row wise)
a=np.arange(9,18).reshape(3,3)

In [149]:
np.vstack((a,ap))

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [ 1,  2,  3]])

In [146]:
np.hstack((a,ad))

array([[ 9, 10, 11,  1],
       [12, 13, 14,  2],
       [15, 16, 17,  3]])

In [144]:
ad=np.arange(1,4)
ad=ad[:,np.newaxis]

In [148]:
ap=np.arange(1,4)


In [151]:
np.split?


Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000011B54745D00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [153]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x0000011B54745C60>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.

In [155]:
np.vsplit?

Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x0000011B54745D00>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]
>>

In [156]:
np.dsplit?

Signature:       np.dsplit(ary, indices_or_sections)
Call signature:  np.dsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function dsplit at 0x0000011B54745DA0>
File:            c:\users\kukad\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split array into multiple sub-arrays along the 3rd axis (depth).

Please refer to the `split` documentation.  `dsplit` is equivalent
to `split` with ``axis=2``, the array is always split along the third
axis provided the array dimension is greater than or equal to 3.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(2, 2, 4)
>>> x
array([[[ 0.,   1.,   2.,   3.],
        [ 4.,   5.,   6.,   7.]],
       [[ 8.,   9.,  10.,  11.],
        [12.,  13.,  14.,  15.]]])
>>> np.dsplit(x, 2)
[array([[[ 0.,  1.],
        [ 4.,  5.]],
       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2

In [168]:
A=np.array([1,2,3,4,5,6])
A

array([1, 2, 3, 4, 5, 6])

In [190]:
#Number split in a range 
np.split(A,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [192]:
np.vsplit(a,[1,2])

[array([[ 9, 10, 11]]), array([[12, 13, 14]]), array([[15, 16, 17]])]

In [193]:
np.hsplit(a,[1,2])

[array([[ 9],
        [12],
        [15]]),
 array([[10],
        [13],
        [16]]),
 array([[11],
        [14],
        [17]])]

In [197]:
t=np.arange(1,28).reshape(3,3,3)
t

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [198]:
np.dsplit(t,3)

[array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]),
 array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]